services:
  # 1. The Database
  mysql-db:
    image: mysql:8.0
    container_name: food_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: food_orders
      MYSQL_USER: ${DB_APP_USER}
      MYSQL_PASSWORD: ${DB_APP_PASSWORD}
    # REMOVED: ports 3306:3306 (Secure internal access only)

  # 2. The Message Broker
  broker:
    image: apache/kafka:latest # Consider pinning this to a specific version later
    container_name: food_kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  # 3. Your Order Service
  order-app:
    build: ./order-service
    container_name: order_service
    ports:
      - "7000:8080" # This is the only port the outside world can see!
    depends_on:
      - mysql-db
      - broker
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/food_orders
      - SPRING_DATASOURCE_USERNAME=${DB_APP_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_APP_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:9092
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # 4. Your Kitchen Service
  kitchen-app:
    build: ./kitchen-service
    container_name: kitchen_service
    depends_on:
      - broker
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=broker:9092