package com.example.orderservice;

import com.example.orderservice.repository.FoodOrderRepository;
import com.example.orderservice.service.DashboardStreamService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Service;

@Service
public class ManagerDltListener {

    private static final Logger log = LoggerFactory.getLogger(ManagerDltListener.class);
    private final FoodOrderRepository repository;
    private final DashboardStreamService streamService;

    public ManagerDltListener(FoodOrderRepository repository, DashboardStreamService streamService) {
        this.repository = repository;
        this.streamService = streamService;
    }

    // Notice we are listening to the default DLT name generated by Spring Kafka
    @KafkaListener(topics = "food-orders-topic.DLT", groupId = "manager-alerts-group")
    public void handleFailedOrders(String failedMessage) {
        log.error("🚨 MANAGER ALERT: Caught a failed order in the Dead Letter Queue -> {}", failedMessage);

        // Remember, our original message format was "ID:FoodItem"
        String[] parts = failedMessage.split(":");
        try {
            Long orderId = Long.parseLong(parts[0]);

            // Update the database so the order isn't stuck "PENDING" forever
            repository.findById(orderId).ifPresent(order -> {
                order.setStatus("FAILED");
                repository.save(order);

                // Blast an alert to the web dashboard!
                streamService.broadcastOrderUpdate("ALERT: Order " + orderId + " FAILED! Kitchen rejected it.");
            });
        } catch (Exception e) {
            log.error("Could not parse failed message: {}", failedMessage);
        }
    }
}